### ISSUE TITLE
illegal multibyte sequence

### ISSUE THREAD

**Issue by zjhxmjl** [vinxv/wenku#1]
F:\mingyu\wenku>wenku.py https://wenku.baidu.com/view/0f8321c8fd0a79563c1e72b1.html
正在获取文档信息...             Finished         耗时:0.00058s
正在获取文档图片...             Finished         耗时:0.00058s
正在获取文档文本...             Finished         耗时:0.00226s
Traceback (most recent call last):
  File "F:\mingyu\wenku\wenku.py", line 222, in <module>
    WenKuClient.fetch(args.url)
  File "F:\mingyu\wenku\wenku.py", line 212, in fetch
    f.write(cls.get_text(doc_id))
  File "C:\Users\one\AppData\Local\Programs\Python\Python39\lib\contextlib.py", line 79, in inner
    return func(*args, **kwds)
  File "F:\mingyu\wenku\wenku.py", line 145, in get_text
    html = cls.session.get(url).content.decode('gb2312')
UnicodeDecodeError: 'gb2312' codec can't decode byte 0xe5 in position 177: illegal multibyte sequence
错误信息如上，老铁

**Comment by vinxv** [comment]
fixed. 
通过 `pip install -U git+https://github.com/vinxv/wenku` 更新。

**Comment by vinxv** [comment]
> F:\mingyu\wenku>wenku.py https://wenku.baidu.com/view/0f8321c8fd0a79563c1e72b1.html
> 正在获取文档信息... Finished 耗时:0.00058s
> 正在获取文档图片... Finished 耗时:0.00058s
> 正在获取文档文本... Finished 耗时:0.00226s
> Traceback (most recent call last):
> File "F:\mingyu\wenku\wenku.py", line 222, in
> WenKuClient.fetch(args.url)
> File "F:\mingyu\wenku\wenku.py", line 212, in fetch
> f.write(cls.get_text(doc_id))
> File "C:\Users\one\AppData\Local\Programs\Python\Python39\lib\contextlib.py", line 79, in inner
> return func(*args, **kwds)
> File "F:\mingyu\wenku\wenku.py", line 145, in get_text
> html = cls.session.get(url).content.decode('gb2312')
> UnicodeDecodeError: 'gb2312' codec can't decode byte 0xe5 in position 177: illegal multibyte sequence
> 错误信息如上，老铁

fixed. 
通过 `pip install -U git+https://github.com/vinxv/wenku` 更新。
